In [1]:
# Importing libraries and date

import pandas as pd
pd.set_option("display.max_columns",None)
df = pd.read_csv("Airbnb_Open_Data.csv")
import numpy as np

C:\Users\Mohamed\AppData\Local\Temp\ipykernel_13940\508486247.py:3: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Airbnb_Open_Data.csv")


In [2]:
# Take a samole of a data

df.sample(10)

id                                              NAME  \
91279  51414728                  Sun-Filled Apartment in Bushwick   
32851  19144943  Cozy & Beautiful Room in Astoria for all seasons   
29741  17427290      Private Bed in Queer Co-Living Space for Men   
64491  36619715                      Pet-Friendly UES One Bedroom   
21534  12894564    East Village, private room with free breakfast   
24540  14554778                     Beautiful Modern Brooklyn Gem   
85003  47948493               Convenient Apt w/ private bathroom!   
43709  25141817   The Sweet Spot 2- Private Apt with a court yard   
61151  34775033              Beautiful Private Room with King Bed   
8743    5830095                                 Large one bedroom   

           host id host_identity_verified        host name  \
91279  63009103410            unconfirmed            Karen   
32851   8722573930               verified             Mars   
29741  25776905516               verified            Marco   
64491  43751879375               verified              Ken   
21534  24597410508            unconfirmed  Adi And Evangel   
24540  30551378358               verified            Kevin   
85003  52080795474            unconfirmed            Weiyi   
43709  65196989483               verified              Joe   
61151  47208775820            unconfirmed             Chii   
8743   69974309980            unconfirmed            Kevin   

      neighbourhood group     neighbourhood       lat      long  \
91279            Brooklyn          Bushwick  40.69864 -73.92827   
32851              Queens  Ditmars Steinway  40.77816 -73.91002   
29741            Brooklyn        Greenpoint  40.72522 -73.95184   
64491           Manhattan   Upper East Side  40.77500 -73.94999   
21534           Manhattan      East Village  40.72598 -73.98856   
24540            Brooklyn     East Flatbush  40.65430 -73.91488   
85003           Manhattan   Upper West Side  40.79546 -73.96452   
43709           Manhattan            Harlem  40.82730 -73.94952   
61151           Manhattan            Harlem  40.82202 -73.95601   
8743            Manhattan   Upper East Side  40.76700 -73.95456   

             country country code instant_bookable cancellation_policy  \
91279  United States           US             True              strict   
32851  United States           US            False              strict   
29741  United States           US             True            moderate   
64491  United States           US             True            flexible   
21534  United States           US            False            flexible   
24540  United States           US            False              strict   
85003  United States           US            False              strict   
43709  United States           US             True            flexible   
61151  United States           US             True              strict   
8743   United States           US            False            moderate   

             room type  Construction year    price service fee  \
91279  Entire home/apt             2003.0     $81         $16    
32851     Private room             2003.0    $756        $151    
29741     Private room             2010.0    $936        $187    
64491  Entire home/apt             2019.0    $514        $103    
21534     Private room             2007.0    $909        $182    
24540  Entire home/apt             2003.0    $482         $96    
85003     Private room             2004.0  $1,137        $227    
43709     Private room             2007.0    $815        $163    
61151     Private room             2015.0    $942        $188    
8743      Private room             2021.0    $763        $153    

       minimum nights  number of reviews last review  reviews per month  \
91279             6.0                2.0   7/24/2017               0.08   
32851             2.0               41.0   5/27/2019               3.18   
29741             3.0                7.0    6/8/2019             

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   id                              102599 non-null  int64  
 1   NAME                            102349 non-null  object 
 2   host id                         102599 non-null  int64  
 3   host_identity_verified          102310 non-null  object 
 4   host name                       102193 non-null  object 
 5   neighbourhood group             102570 non-null  object 
 6   neighbourhood                   102583 non-null  object 
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object 
 10  country code                    102468 non-null  object 
 11  instant_bookable                102494 non-null  object 
 12  cancellation_pol

# The columns i will modify on are :-

- "host_identity_verified"
- "country"
- "price"
- "service fee"
- "last review"

In [4]:
df["host_identity_verified"].unique()

array(['unconfirmed', 'verified', nan], dtype=object)

In [5]:
# Changing the column "host_identity_verified" values

df["host_identity_verified"] = df["host_identity_verified"].str.replace("unconfirmed","NO")
df["host_identity_verified"] = df["host_identity_verified"].str.replace("verified","YES")
df["host_identity_verified"] = df["host_identity_verified"].fillna("")

In [6]:
# Drop country "column" cause it is useless we have "counrty code" column

df = df.drop(columns="country")

In [7]:
df["Construction year"].unique()

array([2020., 2007., 2005., 2009., 2013., 2015., 2004., 2008., 2010.,
       2019., 2018., 2006., 2016., 2017., 2021., 2003., 2011., 2012.,
       2022., 2014.,   nan])

In [8]:
# Changing the type of the "Construction year" column to be numerical

df['Construction year'] = df['Construction year'].replace([np.nan, np.inf, -np.inf], np.nan).fillna(0).astype(int)

In [9]:
df['Construction year'].unique()

array([2020, 2007, 2005, 2009, 2013, 2015, 2004, 2008, 2010, 2019, 2018,
       2006, 2016, 2017, 2021, 2003, 2011, 2012, 2022, 2014,    0])

In [10]:
df["price"].unique()

array(['$966 ', '$142 ', '$620 ', ..., '$1,184 ', '$905 ', '$309 '],
      dtype=object)

In [11]:
# Changing the type of the "price" column to be numerical


df["price"] = df["price"].str.replace("$","")
df["price"] = df["price"].str.replace(",","")
df["price"] = df["price"].astype(float)

C:\Users\Mohamed\AppData\Local\Temp\ipykernel_13940\3947281612.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df["price"] = df["price"].str.replace("$","")


In [12]:
df["price"].unique()

array([ 966.,  142.,  620., ..., 1184.,  905.,  309.])

In [13]:
df["service fee"].unique()

array(['$193 ', '$28 ', '$124 ', '$74 ', '$41 ', '$115 ', '$14 ', '$212 ',
       '$204 ', '$58 ', '$64 ', '$121 ', '$143 ', '$116 ', '$30 ', nan,
       '$56 ', '$95 ', '$27 ', '$210 ', '$163 ', '$235 ', '$106 ', '$55 ',
       '$42 ', '$86 ', '$133 ', '$154 ', '$102 ', '$172 ', '$109 ',
       '$38 ', '$222 ', '$219 ', '$202 ', '$113 ', '$137 ', '$171 ',
       '$12 ', '$87 ', '$183 ', '$92 ', '$73 ', '$146 ', '$180 ', '$67 ',
       '$51 ', '$181 ', '$88 ', '$205 ', '$132 ', '$59 ', '$156 ',
       '$131 ', '$61 ', '$165 ', '$129 ', '$207 ', '$17 ', '$63 ',
       '$147 ', '$105 ', '$48 ', '$114 ', '$80 ', '$23 ', '$11 ', '$149 ',
       '$213 ', '$211 ', '$182 ', '$117 ', '$39 ', '$25 ', '$216 ',
       '$53 ', '$10 ', '$118 ', '$72 ', '$76 ', '$69 ', '$32 ', '$148 ',
       '$101 ', '$177 ', '$49 ', '$100 ', '$168 ', '$13 ', '$152 ',
       '$126 ', '$135 ', '$46 ', '$231 ', '$91 ', '$199 ', '$158 ',
       '$221 ', '$189 ', '$90 ', '$186 ', '$66 ', '$225 ', '$220 ',
       '$19 '

In [14]:
# Changing the type of the "service fee" column to be numerical

df["service fee"] = df["service fee"].str.replace("$","")
df["service fee"] = df["service fee"].astype(float)

C:\Users\Mohamed\AppData\Local\Temp\ipykernel_13940\2454734879.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df["service fee"] = df["service fee"].str.replace("$","")


In [15]:
df["service fee"].unique()

array([193.,  28., 124.,  74.,  41., 115.,  14., 212., 204.,  58.,  64.,
       121., 143., 116.,  30.,  nan,  56.,  95.,  27., 210., 163., 235.,
       106.,  55.,  42.,  86., 133., 154., 102., 172., 109.,  38., 222.,
       219., 202., 113., 137., 171.,  12.,  87., 183.,  92.,  73., 146.,
       180.,  67.,  51., 181.,  88., 205., 132.,  59., 156., 131.,  61.,
       165., 129., 207.,  17.,  63., 147., 105.,  48., 114.,  80.,  23.,
        11., 149., 213., 211., 182., 117.,  39.,  25., 216.,  53.,  10.,
       118.,  72.,  76.,  69.,  32., 148., 101., 177.,  49., 100., 168.,
        13., 152., 126., 135.,  46., 231.,  91., 199., 158., 221., 189.,
        90., 186.,  66., 225., 220.,  19., 238., 119.,  98.,  34., 227.,
       162., 203.,  93., 153.,  71.,  77., 190.,  75., 185.,  97.,  35.,
        37.,  82., 120.,  21., 145.,  65., 144., 108., 194.,  16., 217.,
       188.,  81., 139.,  22., 187., 150.,  50., 176., 151.,  26.,  89.,
       218., 104.,  44.,  79., 240., 175., 192., 21

In [16]:
# Changing the type of the "last review" column to be date

df['last review'] = pd.to_datetime(df['last review'])

In [17]:
# Changing the name of the columns to be the first letter upper

df.columns = df.columns.str.title()

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 25 columns):
 #   Column                          Non-Null Count   Dtype         
---  ------                          --------------   -----         
 0   Id                              102599 non-null  int64         
 1   Name                            102349 non-null  object        
 2   Host Id                         102599 non-null  int64         
 3   Host_Identity_Verified          102599 non-null  object        
 4   Host Name                       102193 non-null  object        
 5   Neighbourhood Group             102570 non-null  object        
 6   Neighbourhood                   102583 non-null  object        
 7   Lat                             102591 non-null  float64       
 8   Long                            102591 non-null  float64       
 9   Country Code                    102468 non-null  object        
 10  Instant_Bookable                102494 non-null  object 

In [19]:
df

Id                                              Name  \
0       1001254                Clean & quiet apt home by the park   
1       1002102                             Skylit Midtown Castle   
2       1002403               THE VILLAGE OF HARLEM....NEW YORK !   
3       1002755                                               NaN   
4       1003689  Entire Apt: Spacious Studio/Loft by central park   
...         ...                                               ...   
102594  6092437                        Spare room in Williamsburg   
102595  6092990                     Best Location near Columbia U   
102596  6093542                    Comfy, bright room in Brooklyn   
102597  6094094                  Big Studio-One Stop from Midtown   
102598  6094647                              585 sf Luxury Studio   

            Host Id Host_Identity_Verified    Host Name Neighbourhood Group  \
0       80014485718                     NO     Madaline            Brooklyn   
1       52335172823                    YES        Jenna           Manhattan   
2       78829239556                               Elise           Manhattan   
3       85098326012                     NO        Garry            Brooklyn   
4       92037596077                    YES       Lyndon           Manhattan   
...             ...                    ...          ...                 ...   
102594  12312296767                    YES         Krik            Brooklyn   
102595  77864383453                     NO        Mifan           Manhattan   
102596  69050334417                     NO        Megan            Brooklyn   
102597  11160591270                     NO  Christopher              Queens   
102598  68170633372                     NO      Rebecca           Manhattan   

              Neighbourhood       Lat      Long Country Code Instant_Bookable  \
0                Kensington  40.64749 -73.97237           US            False   
1                   Midtown  40.75362 -73.98377           US            False   
2                    Harlem  40.80902 -73.94190           US             True   
3              Clinton Hill  40.68514 -73.95976           US             True   
4               East Harlem  40.79851 -73.94399           US            False   
...                     ...       ...       ...          ...              ...   
102594         Williamsburg  40.70862 -73.94651           US            False   
102595  Morningside Heights  40.80460 -73.96545           US             True   
102596           Park Slope  40.67505 -73.98045           US             True   
102597     Long Island City  40.74989 -73.93777           US             True   
102598      Upper West Side  40.76807 -73.98342           US            False   

       Cancellation_Policy        Room Type  Construction Year   Price  \
0                   strict     Private room               2020   966.0   
1                 moderate  Entire home/apt               2007   142.0   
2                 flexible     Private room               2005   620.0   
3                 moderate  Entire home/apt               2005   368.0   
4                 moderate  Entire home/apt               2009   204.0   
...                    ...              ...                ...     ...   
102594            flexible     Private room               2003   844.0   
102595            moderate     Private room               2016   837.0   
102596            moderate     Private room               2009   988.0   
102597              strict  Entire home/apt               2015   546.0   
102598            flexible  Entire home/apt               2010  1032.0   

        Service Fee  Minimum Nights  Number Of Reviews Last Review  \
0             193.0            10.0                9.0  2021-10-19   
1              28.0            30.0               45.0  2022-05-21   
2             124.0             3.0                0.0         NaT   
3              74.0            30.0              270.0  2019-07-05   
4              41.0    

## I think i can not deal with "Name" and "House_Rules" columns depending on my knowledge

# That is it..Thanks